### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by ZhangLiang-Cencen** [FFTAI/Wiki-GRx-Gym#1]
Thanks for your good work!
Could you please tell me how to use tensorboard to watch data?
Thank you!

**Comment by fan-ziqi** [comment]
You can run the following command in the root directory of the project

```bash
tensorboard --logdir=./legged_gym/logs/xxx
```

Please ensure that you are in the Conda or Docker environment

**Comment by ZhangLiang-Cencen** [comment]
Thanks a lot!

**Comment by fan-ziqi** [comment]
I hope your development goes well. This issue will be closed.
